name = "SignalChannels"
uuid = "59ec5e11-ed95-4167-ad38-35055440f478"
version = "6.2.0"
authors = ["Soeren Schoenbrod <soeren.schoenbrod@outlook.de>"]

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
LiveLayoutUnicodePlots = "8b8f1234-5678-9012-3456-789012345678"
PipeChannels = "316ea068-b8d4-4418-b34f-158552ec34f5"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
SoapySDR = "4fa426e6-03fd-45b2-b2dd-25f726820c03"

[extensions]
SignalChannelsSoapySDRExt = "SoapySDR"

[compat]
DSP = "0.7, 0.8"
FixedSizeArrays = "1"
LiveLayoutUnicodePlots = "0.1.0"
PipeChannels = "0.1.1"
SoapyLoopback_jll = "0.1.1"
SoapySDR = "0.5"
UnicodePlots = "3"
Unitful = "1"
julia = "1.12"

[extras]
SoapyLoopback_jll = "8d250ce8-a086-56bd-8a36-e4e8f4202680"
SoapySDR = "4fa426e6-03fd-45b2-b2dd-25f726820c03"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SoapySDR", "SoapyLoopback_jll"]
